version: '3'
services:
  database:
    ports:
      - "5432:5432"
    image: "postgres:12" # use latest official postgres version
    env_file:
      - compose-database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  protobufs:
    image: "namely/protoc-all"
    volumes:
      - ./backend-resources/proto:/defs
      - ./backend-service/entrypoints:/entrypoints
    command: "-f *.proto -l go -o /entrypoints/grpc_entrypoint/gen"
volumes:
  database-data: # named volumes can be managed easier using docker-compose