version: '3'
services:
  database:
    ports:
      - "5432:5432"
    image: "postgres:12" # use latest official postgres version
    env_file:
      - compose-database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  protobufs:
    image: "namely/protoc-all:1.34_5"
    volumes:
      - ./archradar-resources/proto:/defs
      - ./archradar-executor/:/archradar-executor
    command: "-i /opt/include -f *.proto -l go -o /archradar-executor"
volumes:
  database-data: # named volumes can be managed easier using docker-compose