// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common_types.proto

package archradar_grpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on PageInfoItem with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PageInfoItem) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for PageLimit

	// no validation rules for PageSize

	// no validation rules for PageNumber

	// no validation rules for TotalItems

	return nil
}

// PageInfoItemValidationError is the validation error returned by
// PageInfoItem.Validate if the designated constraints aren't met.
type PageInfoItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageInfoItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageInfoItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageInfoItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageInfoItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageInfoItemValidationError) ErrorName() string { return "PageInfoItemValidationError" }

// Error satisfies the builtin error interface
func (e PageInfoItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageInfoItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageInfoItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageInfoItemValidationError{}
